name: safe_steps
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  auto_route: ^7.4.0
  bloc: ^8.0.2
  cloud_firestore: ^4.8.0
  dartz: ^0.10.1
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.1
  firebase_storage: ^11.2.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_mapbox_navigation: ^0.1.7
  google_sign_in: ^6.1.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  logger: ^1.3.0
  sms_advanced: ^1.0.2

dev_dependencies:
  auto_route_generator: ^7.1.1
  bloc_test: ^9.0.2
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0+1	

flutter:
  uses-material-design: true
  generate: true
